-- Add achievement comments table
-- Run this in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS achievement_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  achievement_id BIGINT NOT NULL REFERENCES achievements(id) ON DELETE CASCADE,
  author_id BIGINT NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE achievement_comments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_all" ON achievement_comments FOR ALL USING (true) WITH CHECK (true);
